export default{
  login: "Olukayode08",
  id: 101243426,
  node_id: "U_kgDOBgjaIg",
  avatar_url: "https://avatars.githubusercontent.com/u/101243426?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Olukayode08",
  html_url: "https://github.com/Olukayode08",
  followers_url: "https://api.github.com/users/Olukayode08/followers",
  following_url: "https://api.github.com/users/Olukayode08/following{/other_user}",
  gists_url: "https://api.github.com/users/Olukayode08/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Olukayode08/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Olukayode08/subscriptions",
  organizations_url: "https://api.github.com/users/Olukayode08/orgs",
  repos_url: "https://api.github.com/users/Olukayode08/repos",
  events_url: "https://api.github.com/users/Olukayode08/events{/privacy}",
  received_events_url: "https://api.github.com/users/Olukayode08/received_events",
  type: "User",
  site_admin: false,
  name: "Azeez Olukayode",
  company: 'Myself',
  blog: "Incoming",
  location: 'Working from home',
  email: true,
  hireable: true,
  bio: `Olukayode Azeez, is a frontend developer committed to building problem solving and scalable technological solutions to best suite user's experience.`,
  twitter_username: "_jireazeez",
  public_repos: 12,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2022-03-09T06:52:03Z",
  updated_at: "2022-08-28T08:04:52Z"
}